### PR TITLE
Adding the ability to *ignore* missing mappings.

### PR DESCRIPTION
**Pull request by jvilk**
Adds the (optional) ability to _ignore_ missing mappings. Also, adds a test that exercises this option using the source code of a module from a real-world program, and bumps the version number to `0.2` to indicate the new API functionality.

I encountered this issue with TypeScript. Occasionally, single-line lambdas will not provide a mapping from the `return` statement in the generated JS. For example, `() => "hello"` becomes `function() { return "hello"; }`; the mapping would provide mappings for all parts of the output, save for the `return` keyword.

I could not find a simple use-case that triggered this behavior (the example above does not exhibit the bug); I could only find it in my real-world program (which I use as the test-case).

In the interest of having a working source map, I added an option to `source-map-merger` that _ignores_ these missing ranges in order to produce a mostly complete merged source map. I believe this to be a desirable feature.

Let me know if you have any issues with my coding conventions or style. I look forward to a published v0.2 that I can use!

### CODE REVIEW

**Comment by jvilk** [comment]
I want to note that I'm also going to file a bug with TypeScript about this very issue, since it seems to be a bug.

**Comment by jvilk** [comment]
:heart: thanks! could you also publish v0.2.0 to NPM? I want to officially depend on it in a [grunt task](https://github.com/jvilk/grunt-merge-source-maps) I'm working on.

**Comment by jakobwesthoff** [comment]
Sure. Will do that as soon as I have access my laptop again. Should be tommorow afternoon.

**Comment by jakobwesthoff** [comment]
Finally got to releasing a new version. Furthermore I established semantical-release hooks to make this easier in the future.

**Comment by jvilk** [comment]
Wow, that's awesome. Thanks!

**Pull request merged**
